### ISSUE TITLE
Deploy a Nebari instance at `demo.nebari.dev`

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari-demo#17]
We can host the tutorial here, as well as coordinate on and test our individual NBs. :)

**Comment by pavithraes** [comment]
We also would need to set up an S3/GCS for kbatch demo.

Dharhas mentioned that kbatch won't show any output if we run it locally, but writing to cloud storage will be powerful. I'm paraphrasing and may not be completely accurate, so we can confirm with Dharhas again. :)

**Comment by iameskild** [comment]
[demo.nebari.dev](demo.nebari.dev) is live. 
https://github.com/nebari-dev/demo-nebari-dev

@pavithraes thanks for the heads up! I'm going to open another issue for additional infrastructure changes 💯
