### ISSUE TITLE
Add stocks dataset to GCS

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari-demo#41]
Link to data: https://www.kaggle.com/datasets/debashis74017/stock-market-data-nifty-50-stocks-1-min-data

We can move the complete dataset to cloud storage, and have a smaller subset (with ~5files out of the 100) alongside it for quicker demos.

**Comment by iameskild** [comment]
Uploaded to: nebari-public/nifty_stock_market_data/stock-market-data-india-sample

cc @pavithraes

**Comment by pavithraes** [comment]
Thank you! 🎉

**Comment by iameskild** [comment]
Sorry the link to the full dataset is:
nebari-public/nifty_stock_market_data/stock-market-data-india
